package com.gizmodata.quack.jdbc.sql;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLFeatureNotSupportedException;
import java.sql.SQLWarning;
import java.sql.Statement;

public abstract class SkeletalStatement implements Statement {

    protected static SQLException notSupported(String what) {
        return new SQLFeatureNotSupportedException(what + " is not supported by quack-jdbc");
    }

    @Override public int getMaxFieldSize() { return 0; }
    @Override public void setMaxFieldSize(int max) { /* no-op */ }
    @Override public int getMaxRows() { return 0; }
    @Override public void setMaxRows(int max) { /* no-op */ }
    @Override public void setEscapeProcessing(boolean enable) { /* no-op */ }
    @Override public int getQueryTimeout() { return 0; }
    @Override public void setQueryTimeout(int seconds) { /* no-op */ }
    @Override public void cancel() throws SQLException { throw notSupported("cancel"); }
    @Override public SQLWarning getWarnings() { return null; }
    @Override public void clearWarnings() { /* no-op */ }
    @Override public void setCursorName(String name) { /* no-op */ }
    @Override public int getFetchDirection() { return ResultSet.FETCH_FORWARD; }
    @Override public void setFetchDirection(int direction) { /* no-op */ }
    @Override public int getFetchSize() { return 0; }
    @Override public void setFetchSize(int rows) { /* no-op */ }
    @Override public int getResultSetConcurrency() { return ResultSet.CONCUR_READ_ONLY; }
    @Override public int getResultSetType() { return ResultSet.TYPE_FORWARD_ONLY; }
    @Override public int getResultSetHoldability() { return ResultSet.CLOSE_CURSORS_AT_COMMIT; }
    @Override public void addBatch(String sql) throws SQLException { throw notSupported("batch"); }
    @Override public void clearBatch() throws SQLException { throw notSupported("batch"); }
    @Override public int[] executeBatch() throws SQLException { throw notSupported("batch"); }
    @Override public boolean getMoreResults() { return false; }
    @Override public boolean getMoreResults(int current) { return false; }
    @Override public ResultSet getGeneratedKeys() throws SQLException { throw notSupported("getGeneratedKeys"); }
    @Override public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException { return executeUpdate(sql); }
    @Override public int executeUpdate(String sql, int[] columnIndexes) throws SQLException { return executeUpdate(sql); }
    @Override public int executeUpdate(String sql, String[] columnNames) throws SQLException { return executeUpdate(sql); }
    @Override public boolean execute(String sql, int autoGeneratedKeys) throws SQLException { return execute(sql); }
    @Override public boolean execute(String sql, int[] columnIndexes) throws SQLException { return execute(sql); }
    @Override public boolean execute(String sql, String[] columnNames) throws SQLException { return execute(sql); }
    @Override public boolean isPoolable() { return false; }
    @Override public void setPoolable(boolean poolable) { /* no-op */ }
    @Override public void closeOnCompletion() { /* no-op */ }
    @Override public boolean isCloseOnCompletion() { return false; }
    @Override public <T> T unwrap(Class<T> iface) throws SQLException {
        if (iface.isInstance(this)) return iface.cast(this);
        throw new SQLException("Not a wrapper for " + iface);
    }
    @Override public boolean isWrapperFor(Class<?> iface) { return iface.isInstance(this); }

    public abstract Connection getConnection() throws SQLException;
}
