package com.gizmodata.quack.jdbc.sql;

import java.sql.Array;
import java.sql.Blob;
import java.sql.CallableStatement;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.NClob;
import java.sql.PreparedStatement;
import java.sql.SQLClientInfoException;
import java.sql.SQLException;
import java.sql.SQLFeatureNotSupportedException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Savepoint;
import java.sql.Statement;
import java.sql.Struct;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.Executor;

/** Base class with every {@link Connection} method throwing. Override what we support. */
public abstract class SkeletalConnection implements Connection {

    private static SQLException notSupported(String what) {
        return new SQLFeatureNotSupportedException(what + " is not supported by quack-jdbc");
    }

    @Override public CallableStatement prepareCall(String sql) throws SQLException { throw notSupported("CallableStatement"); }
    @Override public CallableStatement prepareCall(String sql, int rsType, int rsConcurrency) throws SQLException { throw notSupported("CallableStatement"); }
    @Override public CallableStatement prepareCall(String sql, int rsType, int rsConcurrency, int rsHoldability) throws SQLException { throw notSupported("CallableStatement"); }
    @Override public String nativeSQL(String sql) { return sql; }
    @Override public void setReadOnly(boolean readOnly) { /* no-op */ }
    @Override public boolean isReadOnly() { return false; }
    @Override public void setTransactionIsolation(int level) { /* no-op */ }
    @Override public int getTransactionIsolation() { return Connection.TRANSACTION_REPEATABLE_READ; }
    @Override public SQLWarning getWarnings() { return null; }
    @Override public void clearWarnings() { /* no-op */ }
    @Override public Statement createStatement(int rsType, int rsConcurrency) throws SQLException { return createStatement(); }
    @Override public Statement createStatement(int rsType, int rsConcurrency, int rsHoldability) throws SQLException { return createStatement(); }
    @Override public PreparedStatement prepareStatement(String sql, int rsType, int rsConcurrency) throws SQLException { return prepareStatement(sql); }
    @Override public PreparedStatement prepareStatement(String sql, int rsType, int rsConcurrency, int rsHoldability) throws SQLException { return prepareStatement(sql); }
    @Override public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException { return prepareStatement(sql); }
    @Override public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException { return prepareStatement(sql); }
    @Override public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException { return prepareStatement(sql); }
    @Override public Map<String, Class<?>> getTypeMap() { return Map.of(); }
    @Override public void setTypeMap(Map<String, Class<?>> map) throws SQLException {
        // Connection pools (HikariCP) call setTypeMap(new HashMap<>()) during
        // eviction. Accept empty/null maps silently; only non-empty mappings
        // are genuinely unsupported.
        if (map != null && !map.isEmpty()) {
            throw notSupported("setTypeMap with a non-empty type map");
        }
    }
    @Override public void setHoldability(int holdability) { /* no-op */ }
    @Override public int getHoldability() { return java.sql.ResultSet.CLOSE_CURSORS_AT_COMMIT; }
    @Override public Savepoint setSavepoint() throws SQLException { throw notSupported("Savepoints"); }
    @Override public Savepoint setSavepoint(String name) throws SQLException { throw notSupported("Savepoints"); }
    @Override public void rollback(Savepoint savepoint) throws SQLException { throw notSupported("Savepoints"); }
    @Override public void releaseSavepoint(Savepoint savepoint) throws SQLException { throw notSupported("Savepoints"); }
    @Override public Clob createClob() throws SQLException { throw notSupported("Clob"); }
    @Override public Blob createBlob() throws SQLException { throw notSupported("Blob"); }
    @Override public NClob createNClob() throws SQLException { throw notSupported("NClob"); }
    @Override public SQLXML createSQLXML() throws SQLException { throw notSupported("SQLXML"); }
    @Override public boolean isValid(int timeout) {
        if (isClosedQuietly()) return false;
        try (Statement s = createStatement();
             java.sql.ResultSet rs = s.executeQuery("SELECT 1")) {
            return rs.next() && rs.getInt(1) == 1;
        } catch (SQLException e) {
            return false;
        }
    }
    @Override public void setClientInfo(String name, String value) throws SQLClientInfoException { /* no-op */ }
    @Override public void setClientInfo(Properties properties) throws SQLClientInfoException { /* no-op */ }
    @Override public String getClientInfo(String name) { return null; }
    @Override public Properties getClientInfo() { return new Properties(); }
    @Override public Array createArrayOf(String typeName, Object[] elements) {
        java.util.List<Object> values = elements == null
                ? java.util.List.of()
                : new java.util.ArrayList<>(java.util.Arrays.asList(elements));
        return new QuackArray(values, null);
    }
    @Override public Struct createStruct(String typeName, Object[] attributes) {
        return new QuackStruct(typeName, attributes);
    }
    @Override public void abort(Executor executor) throws SQLException { close(); }
    @Override public void setNetworkTimeout(Executor executor, int milliseconds) { /* no-op */ }
    @Override public int getNetworkTimeout() { return 0; }
    @Override public <T> T unwrap(Class<T> iface) throws SQLException {
        if (iface.isInstance(this)) return iface.cast(this);
        throw new SQLException("Not a wrapper for " + iface);
    }
    @Override public boolean isWrapperFor(Class<?> iface) { return iface.isInstance(this); }

    protected boolean isClosedQuietly() {
        try { return isClosed(); } catch (SQLException e) { return true; }
    }

    public abstract DatabaseMetaData getMetaData() throws SQLException;
}
